services:
  web:
    ports:
      - "${WEB_PORT:-8080}:80"
    depends_on:
      api:
        condition: service_healthy

  api:
    ports:
      - "${API_PORT:-8081}:8080"
    environment:
      ALLOW_INSECURE_DEVELOPMENT: "true"
      AWS_S3_BASE_URL: http://localhost:${WEB_PORT:-8080}/api/v1/files
      NODE_ENV: development
